### PR TITLE
symlink versioned jar to unversioned jar

### PR DESCRIPTION
**Pull request by timkpaine**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Hi @timkpaine - thanks for this contribution! Could you please briefly describe which issue this resolves?

**Comment by timkpaine** [comment]
> Hi @timkpaine - thanks for this contribution! Could you please briefly describe which issue this resolves?

I have some cmake code that tries to find this jar according to various conventions, including the "version-complete" name, but similar to shared libraries which often symlink a version-less .so to the versioned .so, I think it makes sense to have "antlr4.jar" for when a specific version isn't required. 

See https://github.com/conda-forge/staged-recipes/pull/24496/commits/eed171bfd9f7901dd92ae998bcb6754d7e06bcd0

**Comment by Tobias-Fischer** [comment]
If it is just for this pull request, can't you do something like
```
# Locate the ANTLR jar file
antlr_jar=$(ls $PREFIX/lib/antlr-*complete.jar)

# Use the located jar file in your build process
-DANTLR_JAR_LOCATION="$antlr_jar"
```
?

I am not familiar with Java packages and their conventions, and while your analogy with shared libraries make sense, I am not sure if this is typical for Java packages. Maybe the other @conda-forge/antlr maintainers know more :)

**Comment by isuruf** [comment]
It looks like debian adds an unversioned symlink exactly for this problem.

**Comment by Tobias-Fischer** [comment]
Thanks @isuruf!

**Pull request merged**
