### PR TITLE
[antlr2] Build for OSX-ARM64 and other new architectures

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@czender, let's see how this goes.  I welcome suggestions (if and) when things start going south.

**Comment by ocefpaf** [comment]
This one will be tough! Not only antlr2 is quite old but compiling it to osx-arm64 won't be easy. My advice is to look into what homebrew is doing.

Also, I'm not an expert and @czender can probably correct me here, but I believe antlr2 is required as a build tool to generate some code, right? Would it be possible to have a nco distro with that code already generated to avoid this dependency?

**Comment by czender** [comment]
@ocefpaf is correct that NCO uses Antlr2.7.7 to build some (about 8 files) of C++ source code. It might be _possible_ to distribute NCO with that pre-generated C++ code, instead of always re-generating those C++ files at build-time. It just depends on your definition of "possible" :) Although the pre-generated files are tractable, compiling and those requires essentially all of the Antlr2.7.7 C++ headers (about 50 more files), and linking those requires the Antlr2 C++ library. All routes require non-trivial infrastructure changes :(

**Comment by czender** [comment]
@xylar I think the `configure` command in the antlr2 branch of `recipes/build.sh` could be altered to avoid the failures on some platforms by disabling csharp, disabling shared, and only enabling c++, i.e., by changing the command to

./configure --prefix=$PREFIX \
            --enable-cxx \
            --disable-python \
            --disable-csharp \
            --disable-shared \
            --disable-java

Antlr2 needs the`javac` and `jar` commands. Those will hopefully already be in the Conda environment. If not, they can be supplied using, e.g., `JAVAC=/usr/bin/javac JAR=/usr/bin/jar configure ...`

**Comment by zklaus** [comment]
Not to butt in here uninvited, but I, too, am keen to see NCO and all the great new quantization and compression stuff in here, so here goes: I've been referring to [this blog post](https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/) for migrating a bunch of feedstocks. Particularly for the present error about unrecognized machine, I think adding `gnuconfig` to build requirements and getting an updated `config.sub` and `config.guess` might help.

I'm happy to push these changes here myself, but didn't want to mess up any ongoing work you might have. Let me know.

**Comment by ocefpaf** [comment]
> and linking those requires the Antlr2 C++ library.

Indeed that would ended up in the same place we are now. So let's try to fix this feedstock instead.

**Comment by xylar** [comment]
@zklaus, feel free to push to this branch.  I'm about to make @czender's suggested changes but after that, please mess around to your heart's content!

**Comment by czender** [comment]
@zklaus Thanks for offering help. Build is currently breaking on osx_arm64 due to outdated config.sub, as you predicted. Please go ahead and address that with your preferred method. This may fix other newer architectures as well...

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@zklaus, you are a magician!  `aarch64` is passing!

**Comment by zklaus** [comment]
Seems everything is working, except for the windows build, which is failing because it is requiring win SDK 8.1, but the oldest we have is 10, if I understand correctly. Really not sure what to do about that. Do you know any Windows experts?

**Comment by xylar** [comment]
One option would be to skip Windows.  We have a working build and don't need new ones for the time being.  @ocefpaf, does that seem okay with you?

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@zklaus, thank you, thank you! Please merge when ready!

**Comment by ocefpaf** [comment]
> One option would be to skip Windows. We have a working build and don't need new ones for the time being. @ocefpaf, does that seem okay with you?

Sure but I'd rather let it fail, merge, and open an issue for it. So we get a breadcrumb trail for why we did this. Skipping in the recipe gives a "clean" image like this was by design and not b/c it failed :-)

**Comment by Tobias-Fischer** [comment]
Lgtm, thanks!

**Comment by Tobias-Fischer** [comment]
We should add the antlr2 branch to the abi migration branches

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
> We should add the antlr2 branch to the abi migration branches

Ah yes. I tried this now here, but probably it needs to be done in `main`, right?

**Comment by Tobias-Fischer** [comment]
Yes it’ll need to be done on main as far as I know

**Pull request merged**
